controller_manager:
  ros__parameters:
   update_rate: 1000
   use_sim_time: true

   joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

   arm_controller:
      type: effort_controllers/JointGroupEffortController

   gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - waist
      - shoulder
      - elbow
      - forearm_roll
      - wrist_angle
      - wrist_rotate
    interface_name: effort               
    command_interfaces:
      - effort                            
    state_interfaces:
      - position 
      - velocity
      - effort                      
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    constraints:
        stopped_velocity_tolerance: 0.02
        goal_time: 1.0
joint_state_broadcaster:
  ros__parameters:
    joints:
      - waist
      - shoulder
      - elbow
      - forearm_roll
      - wrist_angle
      - wrist_rotate
